server:
  port: 8081
  servlet:
    context-path: /javaboy
book:
  name: 三国演义
  author: 罗贯中
redis:
  ip: 192.168.66.128
  ports:
    - 6379
    - 6380
    - 6381
    - 6382
redis2:
  redisList:
    - ip: 192.168.66.128
      port: 6379
    - ip: 192.168.66.129
      port: 6380
    - ip: 192.168.66.130
      port: 6381