<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--
 @作者 江南一点雨
 @公众号 江南一点雨
 @微信号 a_java_boy
 @GitHub https://github.com/lenve
 @博客 http://wangsong.blog.csdn.net
 @网站 http://www.javaboy.org 
 @时间 2019-10-24 9:08
-->
<table>
    <tr>
        <td>error</td>
        <td>${error}</td>
    </tr>
    <tr>
        <td>status</td>
        <td>${status}</td>
    </tr>
    <tr>
        <td>message</td>
        <td>${message}</td>
    </tr>
    <tr>
        <td>path</td>
        <td>${path}</td>
    </tr>
    <tr>
        <td>timestamp</td>
        <td>${timestamp}</td>
    </tr>
</table>
</body>
</html>